travis:
  secure:
    BINSTAR_TOKEN: QaizuTM2/Wn1DI5eQUoNqAuhlICOlereSDX+I5xOqCgaifTbyZ2dLtaq82KRS1I4r2HCAB7VsrlQCvdkLG4jYIOQlFVpKmP2PKcGV8CAeXPvLc8Tk1srSCNCF3VeftjzEhLUns17QzqvNyb9Jh3y8wMv5E87V+2xDZWn0unGPKPwkzdo7aGWrfRvhjduocsF5qlGZYZq2rDVEjLsoDdlbW5IQ3JbE/YNYiqDy77XYq3wLsrAqFAOIJfmP5ozMlwbw6+/30Y32MAL3BSvzqhf0sPD7l86HKSkHS+0K4A8DvBgLfQyv9nS0daLecQYzJOP8UZbdeH7oQJZmMWUIXKUz0Izi1n54n8dGvM+bv88s5HtQseW9zUJsAW5Mk6a/6lD9uavIITlrMQkfKeR/PxCReZzbHyv7OGJUFWzhI4efuWxgE1Gp7HeH1qWRMJXTuqtV/DqCz0DO5qxbbvkneiFwG6TzM3nWOl8RfhGYVZW5OW/Cg3f57ksfc8s6Z52BN2yqNzifRNXwVJ1BPwQ7G/0x3gT9I5LSvlHW+JzKM8MHxa45QuiNtxHFYpa/gWseJMXTQKluz4N/XkYbR4LihCDYsPbtbZBEzVm5cpFsl9N9zlPY0nF/LLxPODHxkrrxXyA7h/XuiF3PkiXQ6Jib5Q35EB6A0DnL8GQgeOZI+Alz9k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
linux_aarch64:
  enabled: true
linux_ppc64le:
  enabled: true
provider:
  linux_ppc64le: default
  linux_aarch64: default
conda_forge_output_validation: true
